### ISSUE TITLE
Support of milleseconds in timespan

### ISSUE THREAD

**Issue by DreamFlasher** [xolox/python-humanfriendly#6]
Input: `hf.parse_timespan("1ms")` or `hf.parse_timespan("1 milliseconds")`
Observed: `60.0`.
Expected: `0.001`

**Comment by xolox** [comment]
Hi and thanks for the feedback!

The `parse_timespan()` and `format_timespan()` pair of functions is intended to parse and format time spans that "the average human" is likely to work with. This explains my choice of units: seconds, minutes, hours, days, weeks and years.

[Wikipedia lists the formal orders of magnitude of time](https://en.wikipedia.org/wiki/Time_(Orders_of_magnitude)) which includes units like nanoseconds, microseconds, milliseconds, kiloseconds, megaseconds, etc. These are not practical units for me to "think in" so I didn't include any of these. However I've just added support for parsing and formatting of milliseconds:

- Parsing works as you would expect it to (your examples work)
- Formatting defaults to rendering fractional seconds like "1.5 seconds" instead of "1 second and 500 milliseconds" because I believe the former to be more human friendly (also: backwards compatibility). You can however get output like "1 second and 500 milliseconds" by calling `format_timespan(..., detailed=True)`.

I'm closing this issue because I believe the problem you reported is resolved. If you don't agree then feel free to reopen this issue or open a new one. Thanks again for the feedback!

<sup>PS. I wonder how long it will take before someone requests to add support for microseconds and/or nanoseconds :-).</sup>

**Comment by DreamFlasher** [comment]
Hi Peter,

first and foremost: Thank you for adding this functionality so quickly. 
I appreciate that you just added it, despite you not seeing a lot value. I needed it because I wanted to parse logs with time information, so yeah I'd assume outside of computer world you don't really need that, but when you work with logs milliseconds is the default (imagine measuring function calls). 
I also believe that the output as you implemented is more humand friendly!

So again: Thank you very much for the quick solution, thank you for your great work!

Marcel

**Comment by turicas** [comment]
You may use [numericalunits](https://pypi.python.org/pypi/numericalunits) to implement other units. ;)
